import os
import logging
from datetime import datetime
from typing import Dict, Any

logger = logging.getLogger("signalforge")


class ReportWriter:
    """
    ReportWriter saves signals as readable Markdown reports.
    """

    def __init__(self, base_dir: str = "reports"):
        """
        Initialize ReportWriter.

        Args:
            base_dir (str): Base directory for reports.
        """
        self.base_dir = base_dir

    def save_report(self, signal: Dict[str, Any]) -> None:
        """
        Save signal as a Markdown report.

        Args:
            signal (dict): Signal data to save.
        """
        today = datetime.utcnow().strftime("%Y-%m-%d")
        wallet = signal.get("wallet", "unknown").replace(":", "_").replace("/", "_")

        dir_path = os.path.join(self.base_dir, today)
        os.makedirs(dir_path, exist_ok=True)

        file_path = os.path.join(dir_path, f"{wallet}.md")

        report_content = self._build_markdown(signal)

        try:
            with open(file_path, "w") as f:
                f.write(report_content)
            logger.info(f"Report saved to {file_path}")
        except Exception as e:
            logger.error(f"Failed to save report to {file_path}: {e}")

    def _build_markdown(self, signal: Dict[str, Any]) -> str:
        """
        Build Markdown content from signal.

        Args:
            signal (dict): Signal data.

        Returns:
            str: Markdown content.
        """
        content = f"# Trading Signal\n\n"
        content += f"- **Wallet**: `{signal.get('wallet')}`\n"
        content += f"- **Signal**: `{signal.get('signal')}`\n"
        content += f"- **Confidence**: `{signal.get('confidence')}`\n"
        content += f"- **Reason**: {signal.get('reason')}\n\n"
        content += f"## AI Comment\n\n{signal.get('ai_comment')}\n\n"
        content += "---\n"
        content += f"_Generated by SignalForge on {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}_"

        return content
