import sqlite3
import os
import logging

logger = logging.getLogger("signalforge")


class Database:
    """
    Database class handles SQLite connection and
    initializes required tables for SignalForge.
    """

    def __init__(self, db_path: str = None):
        """
        Initialize Database class.

        Args:
            db_path (str, optional): Custom path to SQLite database file.
                                     Defaults to project root if None.
        """
        # Auto-detect base directory for Docker & local environments
        if db_path is None:
            base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            self.db_path = os.path.join(base_dir, "signalforge.db")
        else:
            self.db_path = db_path

        self.connection = None
        self._connect()
        self._create_tables()

    def _connect(self) -> None:
        """
        Establish connection to the SQLite database.
        """
        try:
            self.connection = sqlite3.connect(self.db_path)
            logger.info(f"Connected to SQLite database at {self.db_path}")
        except sqlite3.Error as e:
            logger.error(f"Failed to connect to database: {e}")
            self.connection = None

    def _create_tables(self) -> None:
        """
        Create all necessary tables if they do not exist.
        """
        if not self.connection:
            logger.error("Database connection not established. Cannot create tables.")
            return

        try:
            cursor = self.connection.cursor()

            # Table for Signals generated by SignalForge
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS signals (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    wallet TEXT NOT NULL,
                    signal_type TEXT NOT NULL,
                    confidence REAL,
                    reason TEXT,
                    ai_comment TEXT,
                    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
                )
            """)

            # Table for Logs and internal system messages
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS logs (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    level TEXT,
                    message TEXT,
                    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
                )
            """)

            # Table for user-trained Patterns and detection rules
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS patterns (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT,
                    description TEXT,
                    conditions TEXT,
                    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
                )
            """)

            self.connection.commit()
            logger.info("Database tables created successfully.")

        except sqlite3.Error as e:
            logger.error(f"Failed to create tables: {e}")

    def get_connection(self) -> sqlite3.Connection:
        """
        Return the active database connection.

        Returns:
            sqlite3.Connection: Active connection object.
        """
        return self.connection
